### ISSUE TITLE
Very nice work

### ISSUE THREAD

**Issue by mach37** [saneamentoambiental/CodeGenerator#1]
I am very happy to see your help

**Comment by mach37** [comment]
Hi Franciso, i would recommend we maintain our own RAD tool since Halil is not willing to make open source and its very expensive.

I want to replace his grid with a 3rd party open source grid.

**Comment by frchico** [comment]
@mach37 Although the project makes use of the templates folder (I believe the initial idea was to make it possible to change the template without impacting the code) some things are still restricted and need to be codified.

I can help you make the adjustments so that the grid that you are proposing happens to work. Could you share or add the code you use in Views and Controller? So I analyze the impact of this change. It can be simple, like creating a folder with the new template, or you need to encode something for your files to be viewed.
